---
- name: Dependancies of elastalert
  package:
    name: "{{ item }}"
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - libffi-dev
    - libssl-dev

- name: Add elastalert group
  group:
    name: elastalert
    state: present

- name: Add elastalert user
  user:
    name: elastalert
    group: elastalert
    system: yes
    state: present

- name: ElastAlert repository most recent changes
  git:
    repo: https://github.com/Yelp/elastalert.git
    dest: /opt/elastalert

- name: Permission on elastalert directory
  file:
    path: /opt/elastalert
    state: directory
    recurse: yes
    owner: elastalert
    group: elastalert
    
- name: Install the module using pip3
  pip:
    name:
      - setuptools>=11.3
    executable: pip3

- name: execute python script to install module
  shell: python3 /opt/elastalert/setup.py install

- name: module install
  pip:
    name:
      - setuptools>=5.0.0
    executable: pip3

- name: All specified module installation
  shell: pip3 install -e /opt/elastalert/.
